# Generated by Django 4.2.5 on 2023-09-25 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userTier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth_app.usertier'),
        ),
    ]
